codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "25...100"
  status:
    project:
      js:
        target: auto
        threshold: 0%
        base: auto
        paths:
          - "src/client"
      dotnet:
        target: auto
        threshold: 0%
        base: auto
        paths:
          - "src/Conduit"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  branches:
    - master